[project]
name = "coolify-bug-exited"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "flask-cors>=6.0.1",
    "flask-jwt-extended>=4.7.1",
    "gevent>=25.5.1",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.1.1",
]
